version: '3.8'

services:
  # MySQL Database
  mysql-product:
    image: mysql:8.0
    container_name: mysql-product-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: product
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - app-network

  mysql-review:
    image: mysql:8.0
    container_name: mysql-review-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: review
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - app-network
  # Product API Service
  spring-boot-app:
    build:
      context: ./ProductApp-API
      dockerfile: Dockerfile
    container_name: product-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  # Review API Service
  review-service:
    build:
      context: ./ReviewApp-API
      dockerfile: Dockerfile
    container_name: review-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/review?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8082:8082"
    restart: always
    networks:
      - app-network

  # Product UI (React + Nginx)
  product-ui:
    build:
      context: ./ProductApp-UI
      dockerfile: Dockerfile
    container_name: product-ui
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
      - review-service
    environment:
      REACT_APP_API_BASE_URL: http://localhost
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

